language: python
python:
- '3.6'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- ./run_tests.sh
deploy:
  provider: s3
  access_key_id: AKIAJWO3CRW34LY6KQVQ
  secret_access_key:
    secure: EiM7QL38kbdq5noAzmSQFVyW67mZtAkHoe+gEOWOHzp1a0WqdeAp8MluXd+KxtfciTy7lTaVlh+wDneFYVDe1smzrg9haEYM+UyNEM4bowQPA3gA6y2X9bJhBOmv/Q8IwL1hOb4pyG/fKeQz2+iJLJAK5Tp2g6jWPOc+TaGQ5AuiI2adCmLTzv/wggN7BUS4gfFBoU0T1ZitjyYk4wmNyze5cc0n9zCJQpib7URHeW4WSa7yDGk/jXjgF5Z7LpX73v91YBOyzVLzLque2Ucbig1R/fC20VM7nUdmXbdWff4e9TfWqXX2dRB5hwyNhZj2aScm6tZ3xgULejuK8AB7fT3MKxrSEFB6aRJi6U3oZSkaXKqtT3P2qhos6y4Jdvgh5dC9o7j+qt/etYY+/zkyxc5mlO6LGQ1TF95SB9+gH5xqyWS6yYfIHWGpSszyDhEn8+iTQHyDl4UuOXpnnZgZLERUDx39hqpf1WrhNcUIDvR79p4BYVdjQzOCJGbDHAhNDHIce1xhV85tLA0BcXiBMPVPKpp+nIUYUynPKoqa+v13iaC6tL12uM3eSaQBBtXWxl1ItettbecM1FJ92VtWDoMDy0CYHd89cKsdj3UnHQzaSPPDAT+8FvLjjoKQFw01Dqbv+OhtnRLzunN6TiH4s0MbeZU3QT+/tDe2T5818os=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: gtexdictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/gtex-dictionary
    all_branches: true
